<?php

define("KMFOO_APP_PATH", realpath(dirname(__FILE__) . "/app"));

/**
 * The Bootstrap function for the module...
 *
 * @return void
 */
function kmfoo_init() {
    set_include_path(implode(PATH_SEPARATOR, array(
            KMFOO_APP_PATH,
            get_include_path(),
        )
    ));
    $_bootstrapper = new \Kartaca\Kmvc\Bootstrap();
    $_bootstrapper->bootstrap(array(
        "appPath" => KMFOO_APP_PATH,
        "appName" => "foo",
        "defaultNamespace" =>"Kmfoo",
        "appPrefix" => "kmfoo",
    ));
}

