<?php

define("KMFOO_APP_PATH", realpath(dirname(__FILE__) . "/app"));

/**
 * The Bootstrap function for the module...
 *
 * @return void
 */
function kmfoo_init() {
    set_include_path(implode(PATH_SEPARATOR, array(
            KMFOO_APP_PATH,
            get_include_path(),
        )
    ));
    \Kartaca\Kmvc\App::getInstance()->addApp(
        array(
            /**
             * Application path for the module. It contains the controllers and views etc.
             */
            "appPath" => KMFOO_APP_PATH,
            /**
             * Application name for the module. it should be unique for each app. Module name is recommended
             */
            "appName" => "kmfoo",
            /**
             * There is no namespace defined for this module,
             *  if you do please unsilence the line below
             *  and the namespace definitions in the IndexController...
             */ 
            //"defaultNamespace" =>"Kmfoo",
            /**
             * Application prefix where it will be used for the urls.
             *  In order to call the IndexController of this module you have to use: drupal-root/kmfoo/index/index 
             */
            "appPrefix" => "kmfoo",
    ));
}

